name: Build and Deploy Banka Kurye

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.x'
          channel: 'stable'

      - name: Build Web Dashboard
        run: |
          find . -name "pubspec.yaml" -execdir flutter pub get \;
          find . -name "pubspec.yaml" -execdir flutter build web --release --base-href "/banka-kurye-app/" \;

      - name: Upload Web Artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

  deploy-web:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
